pipeline:
  build:
    image: python
    environment:
       # I spun an ec2 ubuntu instance with Redis installed with an elastic IP
      - REDIS_URL= <INSERT URL>
      - PORT= <ENTER PORT>
    commands:
    workspace:
      - cd /app
      - cp . /app
      - cd projectDir
      - pip install --trusted-host pypi.python.org Flask Redis
      - python test1.py

    when:
      branch: [ master ]
      event: [push, pull_request] # trigger step on push and pull events

    publish:
      image: plugins/docker
      username: $DOCKER_USERNAME  # we will inject your dockerhub username using drone secrets.
      password: $DOCKER_PASSWORD # we will inject your dockerhub password using drone secrets.
      email:                     #provide email id
      repo:                       #provide github repo
      tag: latest
      file: Dockerfile
        when:
        branch: [ master ]
        event: [ push ] # step only triggers on push events
services:
  redis:
    image: redis

steps:
- name: slack
  image: plugins/slack
  settings:
    webhook: <https://hooks.slack.com/services/...>
    channel: <your channel>
    link_names: true
    template: >
      {{#success build.status}}
        build {{build.number}} succeeded. Good job. <your email>
      {{else}}
        build {{build.number}} failed. Fix me please. <@channelname> <@someone>
      {{/success}}

